import { createApp } from 'vue'
import { createPinia } from 'pinia'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import './assets/css/global.css'
import './assets/css/home.css'
import './assets/css/catalogue.css'
import './assets/css/formation-detail.css'
import './assets/css/favoris.css'
import './assets/css/contact.css'
import App from './App.vue'
import router from './router'

createApp(App).use(createPinia()).use(router).mount('#app')
